#!/usr/bin/env bash

rm -rf dist/*
esbuild src/index.ts --bundle --external:short-unique-id --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/recurring-task-queue.js --sourcemap --format=iife --global-name=RTQ \
  && esbuild src/index.ts --bundle --external:short-unique-id --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/recurring-task-queue.min.js --minify --format=iife --global-name=RTQ \
  && tsc -d --emitDeclarationOnly --rootDir src --outDir dist \
  && mv dist/index.d.ts dist/recurring-task-queue.d.ts \
  && refup dist/recurring-task-queue.js RTQ \
  && refup dist/recurring-task-queue.min.js RTQ \
  || exit 1
